default: &default
  adapter: postgresql
  encoding: utf8
  username: "<%= ENV.fetch("POSTGRES_USER") %>"
  password: "<%= ENV.fetch("POSTGRES_PASSWORD") %>"
  host: "<%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>"
  port: "<%= ENV.fetch("POSTGRES_PORT") { 5432 } %>"
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "tinysale" } %>_development

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "tinysale" } %>_test

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "tinysale" } %>_production
